### ISSUE TITLE
pml won't start unless mc keeplauncher open is checked

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/Partial-Modification-Loader#1] opened 2016-04-26 01:15 UTC
Version: [MC]PML-9.3.zip
pml won't start unless mc keep launcher open is checked. it closes both the launcher and doesn't seem to open up the mc client (minecraft itself without the launcher) at all.  It just acts like a java error without a crash report.  However the weird thing is after it launched properly with being checked it then  launched  normally afterwords regardless. I then even reset the pml folders to.

**Comment by TheWeatherPony** [comment] 2016-04-26 22:34
This is likely just a delay in the game's launch caused by one of my two obfuscation providers - it needs to download the obfuscation map(s) before the game can start to launch. Since it only needs to download it the first time (and again after deleting its saved copy).

This is also the old repository for the code, and the code now (stupidly) resides split apart in several new repositories.

**Comment by jredfox** [comment] 2016-04-27 01:01
well can you make it so it works whether or not the  keep launcher open launched is running please? It will confuse alot of people on why they can't get it to work.

**Comment by TheWeatherPony** [comment] 2016-04-27 02:16
It does work regardless. It simply requires time to download the absolutely required obfuscations, which it does regardless of if the launcher is kept open or not. The only difference is that people that keep it open the first time can see a message that says that the obfuscations are being download and those that don't keep it open do not (and so are more likely to not know the absolutely required obfuscation maps are being downloaded, which makes them more likely to force close it, which in turn corrupts the state of the downloaded obfuscations to make a multitude of other problems manifest later down the road).

I just tested it on an absolutely fresh install, and it took some time for the game to come up... but it did come up.

**Closed as completed by TheWeatherPony** 2016-04-27 02:16 UTC

**Comment by jredfox** [comment] 2016-04-27 02:55
the first time it didn't come up. I don't know why it is working now? how does pml work is there hidden files elsewhere besides the .minecraft? is it stuck in java memory itself somehow someway?

**Comment by TheWeatherPony** [comment] 2016-04-27 21:02
I once wrote up a technical, yet not very detailed, explanation for how PML's core loading works, and it took up about three pages of solid text - I even said "blaw blaw blaw" in the explanation to gloss over part of the process, as well as some similar things. To try and make it as simple and non-technical as possible (even if that means being inaccurate): PML modifies the earliest Java application loading processes by pairing with and injecting itself into the Java Virtual Machine itself at runtime; in order to inject/weave new code into the application's non-native code, as provided by installed add-ons/mods. Because it injects itself into the JVM at runtime, PML stays loaded and continues functioning until the current copy of Java closes - multiple copies of Java can and do run simultaneously, and PML does not just to other instances.

The specific part that you're wondering about is actually in the add-ons. When the Minecraft application starts up, the application-specific adaptation code figures out what version of the game is in use by snooping through the compiled game code (to look for a version string), which is then given to the add-ons/mods for appropriate actions. The add-ons dealing with obfuscations use the version string to acquire their obfuscation maps (and load them into PML's obfuscation processing code), saving the maps to file for future use (which is why subsequent launches don't require re-downloading the obfuscations, and so take less time to launch). The current place obfuscation add-ons are supposed to store these maps is in the "PML_obfhelp" folder.
Only once PML sets itself up and has provided add-ons/mods the setup opportunities they require is the original application loaded (which gets modified, as it loads, by PML as requested by the add-ons/mods).
